stages:
  - build
  - deploy

variables:
    IMAGE_NAME_TAG: metadata-middleware:latest

build-job:
  stage: build
  only:
      - production
  script:
    - docker build -t $IMAGE_NAME_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_NAME_TAG

deploy-job:
  stage: deploy
  only:
      - production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
