stages:
  - build
  - deploy

variables:
    IMAGE_NAME_TAG: $CI_REGISTRY_IMAGE/metadata-middleware:$CI_COMMIT_REF_SLUG

build-job:
  stage: build
  only:
      - production
      - pprd
  script:
    - docker build -t $IMAGE_NAME_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_NAME_TAG

deploy-job:
  stage: deploy
  only:
      - production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
