apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dataverse

bases:
  - ../../base/

resources:
  - namespace.yml
  - ingress.yml

images:
  - name: gitlab.sciences-po.fr:4567/cdspit/dataverse/metadata-middleware/metadata-middleware
    newTag: 'production'
