apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-middleware

  template:
    metadata:
      labels:
        component: metadata-middleware
        
    spec:
      imagePullSecrets:
        - name: gitlab-cdsp-it
      containers:
      - name: metadata-middleware
        image: gitlab.sciences-po.fr:4567/cdspit/dataverse/metadata-middleware/metadata-middleware:latest
        ports:
          - containerPort: 8000
      imagePullPolicy: Always
